---
#
# Configuration for the Requirements of rqmgtool.
#
# (c) 2022 by flonatel GmbH & Co. KG / Andreas Florath
# 
# SPDX-License-Identifier: GPL-3.0-or-later
# 
# This file is part of rqmgtool.
#   
# rqmgtool is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
# 
# rqmgtool is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with rqmgtool.  If not, see <https://www.gnu.org/licenses/>.
#

type: rqmgtool-config

requirements:
  input:
    default_language: "en_GB"
  inventors:
    - flonatel
  stakeholders:
    - development
    - management
    - users
    - customers

logging:
  # This is the zap logging config
  # https://pkg.go.dev/go.uber.org/zap#Config
  level: debug
  development: true
  # When using json output, the 'levelEncoder' might need
  # to be changed to 'lowerCase'
  #encoding: json
  encoding: console
  encoderConfig:
    timeKey: time
    messageKey: msg
    levelKey: level
    nameKey: name
    callerKey: caller
    levelEncoder: capitalColor
    #levelEncoder: lowerCase
    timeEncoder: iso8601
    durationEncoder: ms
    callerEncoder: partial
    consoleSeparator: ";"
  outputPaths:
    - stderr

output:
  - type: requirements-graph
    params:
      ofile: "artifacts/rqmgtool-graph1.dot"
  - type: topics-graph
    params:
      ofile: "artifacts/rqmgtool-graph2.dot"
  - type: html
    params:
      footer: "html/footer.html"
      header: "html/header.html"
      odir: "artifacts/html"
  - type: latex
    params:
      ofile: "artifacts/rqmgtool.tex"
